// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh9m0E5ptvsbFfHNFCOdbg9sg2Va0wDCM',
    appId: '1:808228911962:web:7eb8a4d497524db1c61163',
    messagingSenderId: '808228911962',
    projectId: 'benesse0714',
    authDomain: 'benesse0714.firebaseapp.com',
    storageBucket: 'benesse0714.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALrsyKvJy_4pgPjtX_lmOl14G8k65U96I',
    appId: '1:808228911962:android:f2152bb1d3b159c7c61163',
    messagingSenderId: '808228911962',
    projectId: 'benesse0714',
    storageBucket: 'benesse0714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBusQvcPoGy28rQ00KXc5R5K7vQQ5nrwvI',
    appId: '1:808228911962:ios:0fdb5a5d171bbb1ac61163',
    messagingSenderId: '808228911962',
    projectId: 'benesse0714',
    storageBucket: 'benesse0714.appspot.com',
    iosBundleId: 'com.example.benesse1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBusQvcPoGy28rQ00KXc5R5K7vQQ5nrwvI',
    appId: '1:808228911962:ios:0fdb5a5d171bbb1ac61163',
    messagingSenderId: '808228911962',
    projectId: 'benesse0714',
    storageBucket: 'benesse0714.appspot.com',
    iosBundleId: 'com.example.benesse1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh9m0E5ptvsbFfHNFCOdbg9sg2Va0wDCM',
    appId: '1:808228911962:web:78bdc4274222d994c61163',
    messagingSenderId: '808228911962',
    projectId: 'benesse0714',
    authDomain: 'benesse0714.firebaseapp.com',
    storageBucket: 'benesse0714.appspot.com',
  );

}